### PR TITLE
Reduce the access token refresh interval rate. 

### PR DESCRIPTION
**Pull request by FreekVandeursen**
Based on https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-oauth-eol-oauth-devstep3

### CODE REVIEW

**Comment by FreekVandeursen** [comment]
@stephangroen Would it be possible to review this PR? The old code will cause problems in less than a month from now

**Comment by bitfactory-jop-mesman** [comment]
@stephangroen Would it be possible to review this PR? The old code will cause problems in less than a month from now.

**Comment by martenvdlp** [comment]
This will cause issues for us as well from the 1st of July. The 60 seconds need to be reduced so that that 9.5 minutes Exact limit for requesting access tokens is not exceeded. Can this be merged?

**Comment by unidoct** [comment]
Is this going to be merged?

**Comment by Eligioo** [comment]
Would be surprised if this will be merged and released on time. I already solved this issue by patching #476 and #482 using `cweagans/composer-patches`. For everybody who is interested:

`composer require cweagans/composer-patches`

Add the following to the `extra` property in your composer file:
As a suggestion I recommend to host the patch files yourself on a gist and don't get them directly from the open PRs.
```json
        "patches": {
            "picqer/exact-php-client": {
                "Reduce the access token refresh interval rate": "https://patch-diff.githubusercontent.com/raw/picqer/exact-php-client/pull/476.patch",
                "Check for valid access token with each request": "https://patch-diff.githubusercontent.com/raw/picqer/exact-php-client/pull/482.patch"
            }
        }
```

After adding the patches to your composer file, run `composter install` and the patches will be applied.

**Comment by FreekVandeursen** [comment]
@casperbakker maybe?

**Comment by casperbakker** [comment]
@FreekVandeursen Yes, will merge now. Thank you for the fix.

**Comment by casperbakker** [comment]
I drafted a new release: https://github.com/picqer/exact-php-client/releases/tag/v3.27.0

**Pull request merged**
