### PR TITLE
2021 11 25 Update from online docs

### PR DESCRIPTION
**Pull request by DannyvdSluijs**
Similar to the work done in PR #489 this pull request does the same.
Given https://github.com/DannyvdSluijs/exact-online-meta-data-tool was updated to
use https://start.exactonline.nl/docs/HlpRestAPIResources.aspx?SourceAction=10 to find all API endpoints instead or relying on the well known endpoints.

### CODE REVIEW

**Comment by DannyvdSluijs** [comment]
I get the PR is rather big and difficult. Is there anything I can do to improve or help?

**Comment by remkobrenters** [comment]
Yeah you are right. It is stalled as it is a big update on a lot of files and properties but I don't see any issues so will put it up for review and merge.

**Review by remkobrenters — APPROVED** [review]

**Comment by stephangroen** [comment]
Just to be sure: Is the removal of the `storable` trait on that many entities correct?

**Comment by DannyvdSluijs** [comment]
> Just to be sure: Is the removal of the `storable` trait on that many entities correct?

I was surprised at the beginning as well. But after reviewing the endpoints they only have `GET` as their supported method. And the [`userscript.js`](https://github.com/picqer/exact-php-client/blob/main/userscript.js#L88) always add the storable. 
So my assumption is that it has been wrongfully added in the past many times. But never used as the endpoints never felt like you could store information.

Glancing over the names of the affected endpoints this assumption still seems very logical.

**Comment by stephangroen** [comment]
Thanks @DannyvdSluijs !

**Pull request merged**
