### PR TITLE
feat: Update according to docs from 2022-10-25; Add CrmDocument and CrmDocumentAttachment classes

### PR DESCRIPTION
**Pull request by DannyvdSluijs**
Solves #588

### CODE REVIEW

**Comment by Eligioo** [comment]
I've tested this PR and it doesn't fully work yet. If you would iterate over the `CrmDocument.Attachments` it tries to lazily load those attachments. Though it tries to load the `Picqer\Financials\Exact\Attachment` class, which does not exists.

**Comment by stephangroen** [comment]
@DannyvdSluijs Can you check on the comment of @Eligioo ?

**Comment by DannyvdSluijs** [comment]
Yes I can. Just didn’t get to it yet. I’m
Hoping to find some time later this week. 

I do have some reservations though. As I suspect we will have more of these issues in the codebase as a result of not checking the type during the code generation.  So one way to approach this could also be to merge this as it covers the basics. And the fix for the use case mentioned by @Eligioo

**Comment by DannyvdSluijs** [comment]
I was able to make a one off fix in the code generation and have updated this MR accordingly. @Eligioo could you verify this fixes your issue?

**Comment by DannyvdSluijs** [comment]
After checking the PR this seems to be complete. As I already addressed the feedback on the 25th of October. It is awaiting confirmation by @Eligioo or merge by @stephangroen

**Review by stephangroen — APPROVED** [review]

**Comment by stephangroen** [comment]
Looks good, thanks @DannyvdSluijs

**Pull request merged**
