### PR TITLE
Fix query string 

### PR DESCRIPTION
**Pull request by DannyvdSluijs**
This first commit has an added test that shows the incorrect query string for each model that has
a query string part to the `$url` property.

A second following commit (still to be added)  will implement the fix and make the test turn green.

This would fix the issue mentioned [here](https://github.com/picqer/exact-php-client/issues/424#issuecomment-1016256789) and confirmed [here](https://github.com/picqer/exact-php-client/issues/424#issuecomment-1016271875).

### CODE REVIEW

**Comment by DannyvdSluijs** [comment]
This has to be checked against #467 as it might contain some BC breakage

**Comment by stephangroen** [comment]
Thanks for the research and clear explanation @DannyvdSluijs. PR #467 was never merged, do you mean PR #478?

If we revert #478, is there a better way to fix the issue tried to solve there?

**Comment by DannyvdSluijs** [comment]
Ahh yes while trying to be clear I simply mixed the PR's as you mentioned indeed.
The solution is (as described in my previous comment under the header `Fix`) to replace any of the calls of `find()` and `findWithSelect()'  with the `get()` [function](https://github.com/picqer/exact-php-client/blob/1fd5da50acc80f8f52114fe877dc5c6ceaf81872/src/Picqer/Financials/Exact/Query/Findable.php#L149-L154) for the endpoints that use query parameters. In my opinion this should have been the fix to begin with but due to issues with the url property from the models that contained some placeholder argument. This PR also addresses that.

**Comment by stephangroen** [comment]
Thanks @DannyvdSluijs. Do you have any comment @remkobrenters? Just curious because you certainly use the library for a wider range of projects and solutions.

**Comment by remkobrenters** [comment]
Thank you @DannyvdSluijs for working out the details. The PR makes sense to bring things back on track. 

Although breaking backwards compatibility is a sad consequence I think almost all of the affected endpoints can be considered as rarely used. And if you are using them the required code changes are small.

**Comment by stephangroen** [comment]
Thanks both :) 

So I think it's fine to merge this and add an extra note of the breaking change in the release notes. It will be a minor release with (small) breaking changes, but to get things back on track as it was broken by a previous release.

**Comment by stephangroen** [comment]
Thanks again @DannyvdSluijs & @remkobrenters :)

**Pull request merged**
