### PR TITLE
#311: Locking callbacks for acquiring new refresh token

### PR DESCRIPTION
**Pull request by TessaBakker**
Added two callbacks for locking and releasing the Connection::acquireAccessToken() method.

See #311 for more information.

### CODE REVIEW

**Comment by jansloot** [comment]
I’m liking the idea but wouldn’t this give a false sense of locking. As the PHP eco system allows for individual processes to run in their own “process” space. 
Perhaps a proper example on how to build a proper locking callback with use of file system and file locks would make it clearer?

Thanks for taking the effort of adding lock support

**Comment by TessaBakker** [comment]
@jansloot I changed the method names, hopefully this make some more sense. Why I didn't implement a file locking system, is that I use Drupal and that has it's own lock and unlocking mechanism.

And nice example would help, feel free to provide one :)

**Comment by stephangroen** [comment]
Thanks @TessaBakker

**Comment by FlubberBeer** [comment]
I'm having some trouble implementing this, could someone make an example to show how this would work in when you have more then 1 worker running.

**Comment by TessaBakker** [comment]
Hi @FlubberBeer,

Here are some PHP examples of locking technics. I didn't test them, but the codes look like something that could work.

https://www.exakat.io/prevent-multiple-php-scripts-at-the-same-time/

You can use the code to implement it with your own callback functions.

**Pull request merged**
