### PR TITLE
Updating the API based on the latest online docs

### PR DESCRIPTION
**Pull request by DannyvdSluijs**
This update was generated using bug fixes in the toolchain this results
in more updates then such an update typically does.

This also fixes https://github.com/picqer/exact-php-client/issues/554

### CODE REVIEW

**Comment by remkobrenters** [comment]
I noticed the `ManufacturingTimeTransactions` but should the `TimeTransaction` https://github.com/picqer/exact-php-client/blob/main/src/Picqer/Financials/Exact/TimeTransaction.php not be refactored to `ProjectTimeTransaction`?

**Comment by DannyvdSluijs** [comment]
I guess we can if you think it is best. I can add a class alias to ensure no breaking changes occur.

**Comment by remkobrenters** [comment]
I think it would clarify the new distinction between the two. The alias sounds like a perfect fallback.

**Comment by DannyvdSluijs** [comment]
> I think it would clarify the new distinction between the two. The alias sounds like a perfect fallback.

See c2ca1e24df0ddb6cbc68424859ce45e82a7256ac for the additions.

**Review by remkobrenters — APPROVED** [review]

**Comment by remkobrenters** [comment]
Forgot to resolve the open comment. @stephangroen Think this one is good to go now.

**Pull request merged**
