### PR TITLE
Update Connection.php to support Webhooks $connection->get($fullendpointurl)

### PR DESCRIPTION
**Pull request by versdivers**
Check if $url has http or https (if it does we assume its a full URL and  we do not reformat the url giving)-> to support webhooks get() function

### CODE REVIEW

**Comment by stephangroen** [comment]
I don't use the webhooks myself, do you use the WebhookSubscriptions entity for this?

**Comment by stephangroen** [comment]
It's not necessary to assign the parsed url to a variable. You could probably do with:

```php
if (is_null(parse_url($url, PHP_URL_SCHEME))) {
    $url = $this->formatUrl($url, $url !== 'current/Me', $url == $this->nextUrl);
}
```
or maybe more readable:
```php
if (substr($url, 0, 4) !== 'http') {
    $url = $this->formatUrl($url, $url !== 'current/Me', $url == $this->nextUrl);
}
```

**Comment by versdivers** [comment]
I think it has almost no to none performance improvements. It is just another way to do it i guess.
Also it can be https which has 5 characters. 

I just check if it has a scheme like you have in your first example but i think (just my opinion) that mine is  more readable.

**Comment by stephangroen** [comment]
> I think it has almost no to none performance improvements.

Indeed, performance wise the impact will be marginal. In most cases assigning to a variable when you're just using it once is not needed, unless it makes it way more readable. The variable name `urlbuild` isn't clear in what it contains.

> Also it can be https which has 5 characters.

That doesn't matter, because the check will still be correct. Either it starts with http or https, both have the first 4 characters http.

I personally think most developers will more easily read the `substr` function and recognise what it does over the `parse_url` function.

**Comment by versdivers** [comment]
I guess we will agree to disagree on this one.
$urlbuild is litterly what it says , it is the build of the url which has a scheme , etc..

But i guess its a matter of preference. Both will work fine.
 My commit here is just so the get function works with webhook subscriptions. It is your github so you can decide how you want it and what you think is best

**Comment by versdivers** [comment]
Is this closed without implementing the changes or are you going to code the changes yourself and patch that?

**Comment by stephangroen** [comment]
I'm going to code them myself, since we agree'd to disagree on this matter. 

`$urlbuild` is just not a clear name to me and I think it's really important nearly everyone should be able to read the code clearly.

**Comment by versdivers** [comment]
I agree , as long as it works i'm happy not matter what the code is.  Thanks!

**Comment by stephangroen** [comment]
Cool, PR's for other changes are always welcome :) It's great to see how this library has grown by all contributions.

**Comment by versdivers** [comment]
I have seen in the new version this has not been updated. Any reason?

**Comment by versdivers** [comment]
Is it possible to update this for future releases?

**Comment by stephangroen** [comment]
It's possible, but don't have the time in the near future.

**Comment by CompactCodeEU** [comment]
This still has not been implented. Resulting in an error after updating.
It should be supported since you get a full endpoint url back on webhooks

**Pull request closed without merging**
