### PR TITLE
Parse JSON dates

### PR DESCRIPTION
**Pull request by aln-1**
Exact will return date value in the format: /Date(5555555555555)/

These need to be set to something more readable.

### CODE REVIEW

**Comment by DannyvdSluijs** [comment]
Thanks for you PR it solves a problem the client is having. However in my view this is a very opinionated solution which will break backwards compatibility and may add additional (unwanted/unneeded) load.  Secondly it would break the typehints on the entities as it would return \DateTime objects instead of the hinted string. Also considering people who aren’t use \DateTime but something like Carbon, Chronos or even are using the Unix time stamp as an string casting it to int. Not even considering one could argue why not use \DateTimeImmutable. 

If any we should see if we could move the json  handling into the handler stack of the Guzzle client, allowing for individual projects to stack more handlers which can upgrade these date string into their appropriate DateTime library class instances.

**Comment by aln-1** [comment]
Hello,

Maybe you missed it but my pr is not returning a DateTime object but a string in the format “2019-07-18T08:29:00”.
You can approach this problem anyway you like, you will get a different opinion from every different developer, my choice was to stringify the values.

**Comment by stephangroen** [comment]
Thanks @aln-1 

As @DannyvdSluijs commented, this will break backwards compatibility. Maybe for now, we can add it as a date parsing example to the README, to provide an easy solution for developers so they know how to parse the date. 

A new major version would benefit from returning better dates.

**Comment by jonmldr** [comment]
Thanks for your contribution, @aln-1!

**Pull request closed without merging**
