### PR TITLE
Update to Guzzle 6

### PR DESCRIPTION
**Pull request by stephangroen**
- Update to Guzzle 6
- Redone oAuth2 dance to require no further dependencies
- Automatically reacquire tokens when needed

### CODE REVIEW

**Comment by MHermsen** [comment]
Stephan Groen,

Just updated my webapplication from PHP 5.3 to 5.4, 5.5 and 5.6.  After testing in the 5.6 version my app works fine.  With our XML API we connect to Exact Online still on Form Authentication.... with still a few days to go before 1 august 2015.

Your API for Exact Online and the other used items Guzzle are pretend for the REST API   Is it possible or are you available to turn this on to the XML API ?

Especially the OAUTH2 is needed for the new authentication and we have no developer in house at the moment to do this.  I am willing to pay for the work...

Please let me know

**Comment by stephangroen** [comment]
@MHermsen I cannot help you implementing this. There is no reason to be concerned about the XML or REST API for you when using this library, because that gets abstracted away. I don't know any devs that have spare time before the 1st of August. Maybe @sebastianberm can help, at least he knows this library well by now :)

**Comment by sebastianberm** [comment]
Hi @MHermsen 

We should be able to help you with this, it'll probably be a close call, but we should be able to make it before the 1st of August.
Can you contact me on sebastian _at_ sebsoft.nl?

**Comment by stephangroen** [comment]
Will merge this after #5 is ready and merged. This will be a v2 because of breaking changes.

**Pull request merged**
