### PR TITLE
allow guzzle 7

### PR DESCRIPTION
**Pull request by it-can**
This pr allows for installing guzzle v7, as far as I can see there is no problems...

https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

### CODE REVIEW

**Comment by abrampl** [comment]
Helo,
It will be awesome to allow guzzle 7

**Comment by it-can** [comment]
@stephangroen can you take a look?

**Comment by it-can** [comment]
@stephangroen can you please merge this and release a new version?

**Comment by BramImhof** [comment]
@stephangroen thanks for this beautiful package! Could you please approve this pull request so we can use it in Laravel 8?

**Comment by earnould** [comment]
I love the package! Can you please approve this PR so that we can use all the Laravel 8 good stuff? Thanks again for giving back to the community!

**Comment by casperbakker** [comment]
Thanks. We fixed this with #442

**Pull request closed without merging**
