### PR TITLE
Added entities for Operation and OperationResource + fillables for ShopOrderRoutingStepPlan + fix type hinting

### PR DESCRIPTION
**Pull request by markjongkind**
Added entities + tests for Operation and OperationResource. Plus added all fillable fields for the entity ShopOrderRoutingStepPlan (they were missing in my previous commit).

Sorry for all the messy commits. :/

### CODE REVIEW

**Comment by DannyvdSluijs** [comment]
@markjongkind first of all thanks for helping provide a more complete API. Frist of all Im not one of the maintainers but I try to contribute to this package as we use it quite heavily. I was wondering, did you by any chance generate the Operation and OperationResource from an older version of the user scripts.js? As with #256 I've searched and replaced all GUID types for string. A quick glance showed seem GUID types in your pull request.

In https://github.com/picqer/exact-php-client/commit/240e8c10573b5a58eeec48a8aed3c122c000da2c#diff-2e74f36e4c594cb4bdc141413fb1e6e0 the userscript.js was updated mapping some Exact Online API types the their respective PHP internal scalar type.

The reason for me butting in, is because gentle by means of small incremental pull requests I'm trying to improve the type hinting go this package.

**Comment by markjongkind** [comment]
@DannyvdSluijs thanks for pointing this out, I must say I'm not aware of userscript.js and/or how this script must be used. I just installed Tampermonkey and now I see what you mean. ;) I'll update this entities and will use Tampermonkey with userscript.js from now on!

**Comment by stephangroen** [comment]
Thank you @markjongkind 

Why did you remove BillOfMaterialMaterials to a non plural version? This change is not backwards compatible.

**Comment by markjongkind** [comment]
@stephangroen I was under the impression that all entities must be singular, so I changed BillOfMaterialMaterial**s** to BillOfMaterialMaterial (and BillOfMaterialVersion**s** to BillOfMaterialVersion).
Is this undesirable? I can change it back to the plural form with a new commit. Let me know!

**Comment by stephangroen** [comment]
My apologies @markjongkind, they should be singular but if you remove the plural versions entirely, it will break for others who are using the plural version.

You can restore the plural versions and alias them for now, so the plurals still work but the singular will be the main class.

See this example: https://github.com/picqer/exact-php-client/blob/master/src/Picqer/Financials/Exact/InvoiceSalesOrders.php where InvoiceSalesOrders got replaced by InvoiceSalesOrder.

**Comment by markjongkind** [comment]
Ah, thanks for the clarification @stephangroen. That's indeed a smart way to handle backwards compatibility. I added the plural classes with an alias in my latest commit.

**Comment by stephangroen** [comment]
Thank you @markjongkind

**Pull request merged**
