### PR TITLE
Added missing propery 'Barcode' to Item

### PR DESCRIPTION
**Pull request by remkobrenters**

### CODE REVIEW

**Comment by remkobrenters** [comment]
@stephangroen are you guys still willing to maintain this repo? Am waiting for this PR and see some more PR's awaiting approval.

**Comment by stephangroen** [comment]
@remkobrenters We're still willing to maintain. Except for this one, the older PR's are one's that require thorough testing and some did contain breaking changes for this version. I've asked about clarification with some things. The newer ones are just days old.

**Comment by remkobrenters** [comment]
@stephangroen a assumed you were busy or something. Thanks for the pull (was waiting for this one).

**Comment by stephangroen** [comment]
@remkobrenters I was, but overlooked your PR :( Thanks for the contribution!

**Pull request merged**
