### PR TITLE
completed Contact entity and Me entity

### PR DESCRIPTION
**Pull request by yohancreemers**

### CODE REVIEW

**Comment by stephangroen** [comment]
Thanks @yohancreemers 

In what situation would you use the findId() method?

**Comment by yohancreemers** [comment]
There are several entities with the property 'Code' (account, contact, costcenter, costunit, item, journal, gl, etc.). For users and third party applications, the Code is often the unique key to which they refer, but the Exact API needs the proper primary key as reference. For example to define the MainContact of an Account, the OrderedBy of a SalesInvoice, or the Item of an SalesInvoiceLine.

**Comment by stephangroen** [comment]
That seems a nice addition, thanks! I suggest to move it to the findable trait, so we have all find-like function stored in there. Other devs will look there to read code about finding stuff with the API.

**Comment by yohancreemers** [comment]
I agree that the Findable trait is the logical place to look for such a function. Found it scary though, as the function relies on methods and properties of the Model class. But that's also the case for other Findable functions, so that might be a different discussion altogether.

**Comment by stephangroen** [comment]
I agree, bit of design flaw :(

We might need to change that but we should keep it outside of this scope :)

**Pull request closed without merging**
