### PR TITLE
Added xml connection

### PR DESCRIPTION
**Pull request by mrdezzods**

### CODE REVIEW

**Comment by mrdezzods** [comment]
Possibility to make xml connection to exact online

**Comment by stephangroen** [comment]
Why do you need to use this?

**Comment by mrdezzods** [comment]
Sometimes, when you want to upload/download items (products) with extra information such as  sales price, suppliers, item group, you may have to make multiple requests if you're working with REST. 
With xml, you can do that all at once, while profiting from the connection which is already initialised for rest request.

**Comment by stephangroen** [comment]
@mrdezzods I'm sorry but I'm not gonna merge this. The client is aimed at the REST API and yes, sometimes that means some more calls. But that shouldn't be a problem and is by design for most REST API's. At this point I think this adds complication to the client and makes it harder for devs to choose what to use.

**Pull request closed without merging**
