### PR TITLE
Update SalesInvoice.php

### PR DESCRIPTION
**Pull request by bertjuuhh**
Updated with all the properties from the documentation

### CODE REVIEW

**Comment by stephangroen** [comment]
Thanks @bertjuuhh !

**Comment by bertjuuhh** [comment]
@stephangroen You're welcome.
I have on quick question, when i use the filter like your example : $item = new Item($connection);
  $item->filter("Code eq '$productcode'");
How do i get the items from it. I used echo $item->propertyname in this case, but it stays empty.

**Comment by stephangroen** [comment]
@bertjuuhh That's a bug, which I have just resolved :)

Filtering could return a single item or multiple items. We didn't account for that yet. I have made an adjustment, which makes filtering always return a collection of items, with just 1 item in the collection in case of a single item return. This ensures the filter() call will always return the same style of result. See: 9f84d7d403551d388300c2792b6dc65533473277

**Comment by bertjuuhh** [comment]
@stephangroen Awesome, thankyou :)
I'll go take a look at it

**Comment by bertjuuhh** [comment]
@stephangroen Do i still need to put an $item->get after the filter to get the results or am i missing something?

**Comment by stephangroen** [comment]
@bertjuuhh No, $item->filter will return an collection (array) of resulting objects, which you can loop over with a foreach.

**Comment by bertjuuhh** [comment]
Oke, thank you!

**Comment by bertjuuhh** [comment]
@stephangroen i found the problem, i was looking up accounts with 'Code' but apparently you need the leading spaces in front of them to get results back.

**Comment by stephangroen** [comment]
@bertjuuhh Yup, they require the leading spaces indeed. This is written somewhere in their docs :)

**Pull request merged**
