### PR TITLE
Added a new Resource SalesPriceListDetails

### PR DESCRIPTION
**Pull request by StefanoGroenland**
For the use of pricelists in exact online.

### CODE REVIEW

**Comment by StefanoGroenland** [comment]
@stephangroen The error is caused because the #233 isn't merged yet. So the test fails. Forgot to clean it up after. If you mind, i can revert it and make a new PR.

**Comment by StefanoGroenland** [comment]
@stephangroen is this going to be merged ? Need the functionality.

**Comment by stephangroen** [comment]
Can you resolve the conflicts?

**Comment by StefanoGroenland** [comment]
I decided to fork the repo.

**Pull request closed without merging**
