### PR TITLE
Update PurchaseInvoice.php

### PR DESCRIPTION
**Pull request by justijndepover**
renamed function name

### CODE REVIEW

**Comment by stephangroen** [comment]
Good find! Can you also add a `getSalesInvoiceLines` which calls the renamed function? Otherwise it will break existing versions.

**Comment by justijndepover** [comment]
The function requires a $select or a $top=1 statement. Should I implement it like this?
```php
public function getPurchaseInvoiceLines($statement) {
    if(array_key_exists('__deferred', $this->attributes['PurchaseInvoiceLines'])) {
        $this->attributes['PurchaseInvoiceLines'] = (new PurchaseInvoiceLine($this->connection()))->filter("InvoiceID eq guid'{$this->ID}'", "", "", $statement);
    }
    return $this->attributes['PurchaseInvoiceLines'];
}

$purchaseinvoice->getPurchaseInvoiceLines(['$select' => 'Amount,CostCenter']);
```

**Comment by stephangroen** [comment]
Given your first change I would just add a function after your change:

```php
/**
 * @deprecated This function got renamed, still here for backward compatibility. To be removed in next major version. 
 */
public function getSalesInvoiceLines()
{
    return $this->getPurchaseInvoiceLines();
}
```

**Comment by justijndepover** [comment]
done

**Comment by stephangroen** [comment]
Alright, but now the getPurchaseInvoiceLines function requires a `$statement` param, which it didn't before. So anyone using it without supplying the param will get an error.

**Comment by justijndepover** [comment]
This function 
```php
(new PurchaseInvoiceLine($this->connection()))->filter("InvoiceID eq guid'{$this->ID}'")
```
requires a `$top` or `$select` statement. So I'm guessing no one even used this function since it always returns an API exception.

**Comment by stephangroen** [comment]
Ah, thanks. So then we should also add the statement param to the `getSalesInvoiceLines` function that's added.

**Comment by justijndepover** [comment]
You're right, forgot about that.

**Comment by justijndepover** [comment]
If you really wan't to be sure it's backwards compatible I can add a default value like this: `$statement = ''` to the argument list

**Comment by stephangroen** [comment]
That would be great @justijndepover, this will prevent any fatal errors. I think you're right about the current usages, but I don't want to break backwards compatibility just to be certain.

**Comment by justijndepover** [comment]
done

**Pull request merged**
