### PR TITLE
Update Guzzle to 7.0

### PR DESCRIPTION
**Pull request by stemis**
Adresses #435 

Guzzle 7.0 has become standard now for some packages such as [laravel 8.0](https://github.com/laravel/laravel/blob/ca30159cabe05675fa268f49acdf93ef12480b01/composer.json#L14).

We cannot upgrade to laravel `8.0` until all packages have a guzzle minimum of `7.0`.

This PR bumps guzzle to version `7.0` which has a minimum php version of `7.2`.
Also bumps PHPUnit to `8.5`.

Also drops supports for outdated PHP versions which should make this repo easier to maintain in the future.

A new `MAJOR` release is needed for this one as it is a MAJOR php version change.

### CODE REVIEW

**Comment by pbeernink** [comment]
I personally prefer the way it is handled in #440 as that one doesn't "force" the use of Guzzle 7.
In our project we depend on other packages which have Guzzle 6 as dependency (those also have pull requests waiting).
When only allowing Guzzle 7, it makes it impossible to update the Exact library until all those packages are fixed.

**Comment by abrampl** [comment]
When we can expected this merge ??

**Comment by rickgoemans** [comment]
Looking forward for this merge!

@stephangroen can you take a look at this since Laravel 8 is starting to more and more being used right now.

**Comment by abrampl** [comment]
Hi 
@stephangroen Laravel 8 is now framework, that are used in all new projects.  It will be awesome to merge this asap :)

**Comment by MaartenWaegeman** [comment]
Hey @stephangroen, I'm also stuck like everyone above, because Laravel 8.0 requires Guzzle 7, and Picqer relies on Guzzle 6. Composer won't install both versions. Would it be possible to merge this in, so we can continue to use this fantastic Exact connector? Thanks in advance!

**Comment by rickgoemans** [comment]
For those who aren't familiar with using forked packages, here's how you can use it until the someone of picqer approved and merged this pull request:

```
"require": {
   "picqer/exact-php-client": "dev-guzzle-phpunit-update",
},
"repositories": [
  {
    "type": "vcs",
    "url": "https://github.com/stemis/exact-php-client"
  }
],
```

This uses the forked repo of the creator of this pull request.

**Comment by casperbakker** [comment]
This should be handled like #440 is handled. If you remove 6.0 when adding 7.0, migrating existing projects is very hard.

**Comment by stemis** [comment]
Thanks for your input @casperbakker . When I made the PR I did not see the mentioned PR as it was not mentioned in the original issue.

> If you remove 6.0 when adding 7.0, migrating existing projects is very hard.

In the past, this package has used different major versions on guzzle upgrades, I did the same thing with the thought that it also makes the package easier to maintain as you don't have to support version combinations.

I agree that the solution in #440 also works. However, that PR lacks the adjustment of the Travis file as it must also be adjusted to test with both Guzzle versions. Right now I don't believe the CI is integrated with Github yet so it's hard to test.

I don't mind which one has the preference for you, it's your(Picqer's) package so it's your choice. I just like this package to be compatible with Guzzle 7 so we can do our laravel upgrade.

**Comment by casperbakker** [comment]
In previous Guzzle versions there were major breaking changes which made it very hard for packages to support multiple versions. I don't know if it was in versions 5>6, but definitely in the 3-4-5 era. But now there are no backwards compatibility issues when upgrading Guzzle, so support as many currently used Guzzle versions is preferable.

**Comment by casperbakker** [comment]
I think upgrading the PHP version and phpunit version is fine, and great that you updated the Travis config.

> I agree that the solution in #440 also works. However, that PR lacks the adjustment of the Travis file as it must also be adjusted to test with both Guzzle versions.

The tests in this package are not so complete that we really need to setup testing for both Guzzle 6 and 7, in my opinion.

> A new MAJOR release is needed for this one as it is a MAJOR php version change.

I don't think it is needed to go to version 4 per se, as composer will handle the php and guzzle requirements together to figure out which version is installable. But I will leave that to @stephangroen

**Comment by rickgoemans** [comment]
Why don't we just combine the 2 PR's, taking this as reference since this also updates Travis, PHP version and PHPUnit. And allow both Guzzle 6 and 7 as in #440?

This solves all are problems.

**Review by stephangroen — APPROVED** [review]

**Comment by stephangroen** [comment]
Sorry for the late response!

**Comment by stemis** [comment]
Excellent, thanks! @stephangroen  @casperbakker

**Pull request merged**
